---
# tasks file for glusterfs
- name: disable selinux
  selinux:
    state: disabled
  when: ansible_selinux.status != 'disabled'

- name: reboot all machines
  reboot:
    msg: "Rebooting machines after disabling SELinux..."
  when: ansible_selinux.status != 'disabled'
  tags:
  - never

- name: create physical volumes and volume groups for glusterfs
  lvg:
    vg: glusterfs-{{ item.vg }}
    pvs: "{{ item.pvs }}"
  with_items: "{{ glusterfs_lvm }}"
  tags:
  - never

- name: create logical volumes for glusterfs
  lvol:
    vg: glusterfs-{{ item.vg }}
    lv: glusterfs-{{ item.lv }}
    size: 100%FREE
  with_items: "{{ glusterfs_lvm }}"
  tags:
  - never

- name: format glusterfs logical volumes
  filesystem:
    dev: /dev/mapper/glusterfs--{{ item.vg }}-glusterfs--{{ item.lv }}
    fstype: "{% if item.fstype | length %}{{ item.fstype }}{% else %}{{ glusterfs_fstype }}{% endif %}"
    opts: "{% if item.opts | length %}{{ item.opts }}{% else %}{{ glusterfs_opts }}{% endif %}"
  with_items: "{{ glusterfs_lvm }}"
  tags:
  - never

- name: create directories for glusterfs volumes and bricks
  file:
    path: "{{ glusterfs_dir }}/{{ item.lv }}/brick-01"
    state: directory
  with_items: "{{ glusterfs_lvm }}"

- name: mount glusterfs logical volumes
  mount:
    path: "{{ glusterfs_dir }}/{{ item.lv }}/brick-01"
    src: /dev/mapper/glusterfs--{{ item.vg }}-glusterfs--{{ item.lv }}
    fstype: "{% if item.fstype | length %}{{ item.fstype }}{% else %}{{ glusterfs_fstype }}{% endif %}"
    opts: "{% if item.mount_opts | length %}{{ item.mount_opts }}{% else %}{{ glusterfs_mount_opts }}{% endif %}"
    dump: "{% if item.mount_dump | length %}{{ item.mount_dump }}{% else %}{{ glusterfs_mount_dump }}{% endif %}"
    passno: "{% if item.mount_passno | length %}{{ item.mount_passno }}{% else %}{{ glusterfs_mount_passno }}{% endif %}"
    state: mounted
  with_items: "{{ glusterfs_lvm }}"
  tags:
  - never

- name: disable swap
  command: /usr/sbin/swapoff -a
  when: ansible_swaptotal_mb > 0

- name: remove swapfile from /etc/fstab
  mount:
    path: swap
    fstype: swap
    state: absent

- name: tuning kernel for glusterfs (vm.swappiness)
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    ignoreerrors: yes
    sysctl_set: yes

- name: add glusterfs repo
  yum:
    name: centos-release-gluster{{ glusterfs_version }}
    state: present

- name: install glusterfs
  yum:
    name:
    - glusterfs
    - glusterfs-cli
    - glusterfs-libs
    - glusterfs-server
    state: present

- name: start glusterd
  systemd:
    name: glusterd
    enabled: yes
    state: started

- name: open firewall ports for glusterfs
  firewalld:
    immediate: yes
    offline: yes
    permanent: yes
    port: "{{ item }}/tcp"
    state: enabled
  with_items:
  - 24007-24008
  - "{{ glusterfs_brick_ports }}"

- name: add glusterfs servers to cluster
  command: /usr/sbin/gluster peer probe {{ item }}
  delegate_to: "{{ ansible_play_batch | first }}"
  run_once: true
  with_items: "{{ ansible_play_batch | !first }}"
  tags:
  - never

- name: probe first server
  command: /usr/sbin/gluster peer probe "{{ ansible_play_batch | first }}"
  delegate_to: "{{ ansible_play_batch[1] }}"
  run_once: true
  tags:
  - never

- name: create glusterfs volumes and set options
  gluster_volume:
    name: "{{ item.name }}"
    bricks: "{% for dir in item.brick_dirs %}{{ glusterfs_dir }}/{{ dir }}/brick-01/brick{{ ',' if not loop.last }}{% endfor %}"
    replicas: "{{ item.replicas }}"
    cluster: "{{ item.cluster }}"
    options:
      auth.allow: "{% for host in item.auth_allow %}{{ host }}{{ ',' if not loop.last }}{% endfor %}"
    state: present
  with_items: "{{ glusterfs_volumes }}"
  tags:
  - never
